### ISSUE TITLE
Save State Client Response

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#170] opened 2023-08-14 21:44 UTC
When running the `save-state` client command, the client always receives back an error, even when the snapshot is created successfully. Fix this so that the `save-state` command reports its success as well as a summary of its result

**Comment by trevorbernard** [comment] 2023-10-08 21:32
The problem is that the `mina-indexer client` expects a serialized version of the response but it's returning a string. I will close this issue when the following PR gets merged: https://github.com/Granola-Team/mina-indexer/pull/218

**Comment by trevorbernard** [comment] 2023-10-08 21:55
This issue disappear when we removed the save snapshot feature

**Closed by trevorbernard** 2023-10-08 21:55 UTC
Labels: bug
