### ISSUE TITLE
Problem: a transaction is missing

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1071] opened 2024-06-06 04:11 UTC
Consider transaction `CkpZLKv4WLHTwRKLwZcaFdVzrfCXnSofZTroT6Y353np1X4MAJ4ed` which appears here on MinaExplorer.com: https://minaexplorer.com/transaction/CkpZLKv4WLHTwRKLwZcaFdVzrfCXnSofZTroT6Y353np1X4MAJ4ed

It is in block 3825, for which we now have data, in prod.

When I enter that transaction hash into the search bar, it says that we have no results. Yet, notice that the transaction is canonical on minaexplorer.com.

When I enter that transaction hash into the TXN HASH of our user commands page, there are results provided I select `non-canonical`. However, the block *is* canonical according to Mina Explorer.

**Comment by Isaac-DeFrain** [comment] 2024-06-06 05:39
Related #1072. I know what the problem is. It will be fixed quickly.

**Comment by trevorbernard** [comment] 2024-06-10 14:51
A little more context around this bug. This only occurs when there is a non-canonical block at the same height having 1 or more transactions with the same hash on certain column families. It's stems from the fact that in order to uniquely identify a transaction we must also take into consideration which block it's in.

**Comment by robinbb** [comment] 2024-06-10 19:09
There is still a problem, however, so we must not yet close this. CkpZLKv4WLHTwRKLwZcaFdVzrfCXnSofZTroT6Y353np1X4MAJ4ed in the search bar results in a spotlight page with Canonical:false. Yet, there is another block that exists for which Canonical:true for this same hash. So, we are taking ppl to the wrong spotlight record. Or, there should be multiple records on the spotlight page.

**Comment by Isaac-DeFrain** [comment] 2024-06-10 19:11
On it

**Comment by trevorbernard** [comment] 2024-06-12 05:06
This is resolved

**Comment by trevorbernard** [comment] 2024-06-12 14:57
It's resolved because Nathan produced a frontend fix to include the the state_hash and txn hash.

**Comment by Isaac-DeFrain** [comment] 2024-06-12 14:58
Related to #1101

**Comment by Isaac-DeFrain** [comment] 2024-06-12 15:00
It is apparently not resolved...
![image](https://github.com/Granola-Team/mina-indexer/assets/42081488/064cd8a0-77f6-4941-bfbc-2fc673a7cef0)

**Comment by trevorbernard** [comment] 2024-06-12 15:03
Oh I see. This is coming from the global search.

**Closed** 2024-06-12 19:00 UTC
Labels: Bug, Data
