### ISSUE TITLE
Problem: B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va has too many records

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1108] opened 2024-06-11 20:51 UTC
Paste B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va into the search bar, you will see too many idential records in the spotlight page.

**Comment by trevorbernard** [comment] 2024-06-11 21:34
This is likely a duplicate of the one @Isaac-DeFrain suggested I do

**Comment by trevorbernard** [comment] 2024-06-12 15:53
@robinbb The issue is closed but the indexer in production hasn't deployed the new code yet

**Comment by robinbb** [comment] 2024-06-12 16:26
Yeah, you're right, Trevor. My bad. I was too hasty. I see it is fixed, now.

**Closed** 2024-06-12 16:26 UTC
Labels: Data
