### ISSUE TITLE
Problem: indexer logging during block ingestion needs improvement

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#380] opened 2024-01-23 23:58 UTC
Reporting during ingestion and upon completion has some errors

**Comment by trevorbernard** [comment] 2024-02-04 13:48
Has this been resolved @Isaac-DeFrain? I vaguely remember you adding some debug logging for ingestion

**Comment by Isaac-DeFrain** [comment] 2024-02-10 01:41
@trevorbernard we should further improve the log messages. Let's pair at some point and polish it up

**Comment by robinbb** [comment] 2024-03-07 01:33
@Isaac-DeFrain @trevorbernard This has become an important issue, and more urgent, because, during the attempt to ingest the full set of blocks, little is seen in the logs about what is happening, and progress is too slow. Perhaps some debugging the the ingestion is also necessary.

**Comment by jhult** [comment] 2024-03-28 20:05
@robinbb, @Isaac-DeFrain

Perhaps #608 is a dupe of this.

**Comment by robinbb** [comment] 2024-03-28 21:11
Yup. Will close as dup.

**Closed by robinbb** 2024-03-28 21:11 UTC
Labels: enhancement, good first issue, logging
