### ISSUE TITLE
Use the new `berkeley` precomputed block parsers after block 359604

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1253] opened 2024-07-08 15:44 UTC
This is the new post hard-fork chain aka Berkeley mainnet.

**Comment by trevorbernard** [comment] 2024-07-16 13:26
> Easy

I like your style

**Comment by jhult** [comment] 2024-09-19 17:39
Dupe of #602. Will be handled in #602.

**Closed by jhult** 2024-09-19 17:39 UTC
Labels: Berkeley
