### ISSUE TITLE
Filtering stakes by username does not produce expected result

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1592] opened 2024-10-03 17:43 UTC
Query:
```
query StakingLedgersQuery($limit: Int = 10, $sort_by: StakeSortByInput!, $query: StakeQueryInput!) {
  stakes(limit: $limit, sortBy: $sort_by, query: $query) {   
    username   
  }
}
```

Variables
```
{
  "limit": 1000,
  "sort_by": "STAKE_DESC",
  "query": {
    "username":"Auro Wallet",
    "epoch":79
  }
}
```

result:
```
{
  "data": {
    "stakes": []
  }
}
```

Once `username` is removed from query, AuroWallet appears as the 4th result

**Comment by Isaac-DeFrain** [comment] 2024-10-04 18:21
Closing as a dupe of #1328

**Closed by Isaac-DeFrain** 2024-10-04 18:21 UTC
Labels: Bug
