### ISSUE TITLE
Support the archive node API from O(1) Labs

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#735] opened 2024-04-03 00:52 UTC
https://github.com/o1-labs/archive-node-api

**Comment by trevorbernard** [comment] 2024-04-03 18:53
Note: https://github.com/Granola-Team/mina-indexer/issues/357

**Comment by jhult** [comment] 2024-05-09 17:23
@robinbb, is this a dupe of #357?

**Comment by robinbb** [comment] 2024-05-21 00:34
> @robinbb, is this a dupe of #357?

Unknown.

**Comment by Isaac-DeFrain** [comment] 2024-06-12 20:03
Closing as it is a dupe of #357

**Closed by Isaac-DeFrain** 2024-06-12 20:03 UTC
Labels: GraphQL
